### ISSUE TITLE
关于数首诗的问题

### ISSUE THREAD

**Issue by sansuihanshi** [THUNLP-AIPoet/Resources#1]
61贾曾的《有所思》与100刘希夷的《白头吟》重合度甚高，或者说前者是后者的一部分，刘希夷早于贾曾数十年，而且我们现在一般认为‘年年岁岁花相似，岁岁年年人不同’是刘希夷的作品。把《有所思》排到《白头吟》前面，是否是算法将‘年年岁岁花相似，岁岁年年人不同’的影响力加到了《有所思》身上？

同样的情况见于145，诗中用了‘伐木丁丁，鸟鸣嘤嘤’，‘如切如磋，如琢如磨’，两句诗经中的名句，而这首诗本身相对没有名气，是否是诗经名句给这首诗加了分？

6与214似为重复。

另外83的‘纨裤不饿死’的‘裤’应该是错别字。

**Comment by gzp9595** [comment]
谢谢您的关切！虽然客观地保留您提到的这三首诗也是合理的，但鉴于这里是精选300首，所以思考再三，还是决定接受您的建议，将原创性不强（直接借用更早的诗句）、或者高度相似的三首诗删去了。另外递补了三首。另：“纨绔““纨裤”应均可，也改用“纨绔”。
